### ISSUE TITLE
rabbitmq-server patch question

### ISSUE THREAD

**Issue by timofei-durakov** [rabbitmq/rabbitmq-clusterer#1]
Hi.
When I want to use this plugin with rabbitmq-server 3.5.3 what is the easiest way to patch server?
Should i build server from sources, or I can install it from packet? If I decide to build and install server from sources, what would be the correct way to do it? If I install it from package how should I use your patch for rabbitmq-server?

**Comment by videlalvaro** [comment]
The patch just modifies a couple ENV variables on the `rabbitmq-server` script, so how you install it doesn't matter too much, see:

https://github.com/rabbitmq/rabbitmq-clusterer/blob/master/rabbitmq-server.patch

**Comment by timofei-durakov** [comment]
@videlalvaro yes, I saw, these line are confusing:
`With RabbitMQ versions earlier than 3.5.4, it is necessary to apply a rabbitmq-server patch and re-compile the broker.` It seems that a lot of work should be done before plugin could be installed:)

**Comment by timofei-durakov** [comment]
BTW, on which file should I apply patch if rabbitmq-server was installed from .deb package?

**Comment by michaelklishin** [comment]
@timofei-durakov you need to patch `rabbitmq-server`.

**Comment by michaelklishin** [comment]
The ability to change boot module via `RABBITMQ_BOOT_MODULE` was added in `3.5.4`, so the patch changes VM arguments. In `3.5.4` and later releases, both values changed by the patch can be set via environment variables.

We will provide a binary build of the plugin on our [Community Plugins](https://www.rabbitmq.com/community-plugins.html) page.

**Comment by michaelklishin** [comment]
An update on this: we'll release a binary build after `3.5.4`, which should be released tomorrow.
