### ISSUE TITLE
Cluster with one node

### ISSUE THREAD

**Issue by guzmo** [rabbitmq/rabbitmq-clusterer#14]
Hey,

Im trying to automatically create a cluster at startup but I can't get the cluster to start because the first docker container that starts is alone and because of that its a single node in the cluster.config file.

I will keep increasing the config file when more rabbitmqs gets started but I need to be able to start one at first.

Below is the first config that will be created.

[{version, 1},
 {nodes, ['rabbit@10.10.10.10']},
 {gospel, {node, 'rabbit@10.10.10.10'}
}].

Next container that starts will be

[{version, 1},
 {nodes, ['rabbit@10.10.10.10', 'rabbit@10.10.10.11']},
 {gospel, {node, 'rabbit@10.10.10.10'}
}].

PS: dont care about the IP:s I just faked em for show.

The only thing I get from the MQ is "Clusterer stopping node now."

Cheers

**Comment by michaelklishin** [comment]
This means the plugin believes the cluster is formed and this node has no peers to wait for.

Please ask questions on rabbitmq-discuss in the future.

**Comment by michaelklishin** [comment]
Also, aweber/rabbitmq-autocluster may suit your Dockery case better.
