### ISSUE TITLE
Shipping this Plugin as officially supported

### ISSUE THREAD

**Issue by JustinPullen** [rabbitmq/rabbitmq-clusterer#15]
I was just curious about this plugin being shipped as officially supported and in the distributions.   I assume there is a very good reason it is not but this plugin could really change the Rabbitmq and Docker landscape with some minor changes to the docker-library/rabbitmq.  (I may have already made them and have them ready for a PR) However I am sure there is a reason and just wanted to ask the creators and team members on if this ever could be the case. 

Justin P.

**Comment by michaelklishin** [comment]
There are no plans to distribute this plugin with RabbitMQ. We really hope in 6-12 months it won't be necessary.
