### ISSUE TITLE
rabbit_table:wait_for_replicated/0 is gone in `stable`

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-clusterer#19]
This plugin relies on `rabbit_table:wait_for_replicated/0` which is gone in `stable` (upcoming `3.6.7`), or more specifically in https://github.com/rabbitmq/rabbitmq-server/issues/1033.

While the goal of https://github.com/rabbitmq/rabbitmq-server/issues/1033 is to make this plugin unnecessary for most, we should either

 * Update and produce a new release of this plugin
 * Bring that function back (it'd pass `false` to `rabbit_table:wait_for_replicated/1`)

The latter should also work for compatibility for master and older/customer builds of this plugin, so we will do that.

**Comment by gerhard** [comment]
Closed in rabbitmq/rabbitmq-server#1075
