### ISSUE TITLE
rabbitmq_server-3.6.15安装失败

### ISSUE THREAD

**Issue by SeekingPlumBlossoms** [rabbitmq/rabbitmq-clusterer#24]
[root@VM-66-113 sbin]# ./rabbitmq-server start

BOOT FAILED
===========

Error description:
   noproc

Log files (may contain more information):
   /data/mq/rabbitmq_server-3.6.15/var/log/rabbitmq/rabbit@VM-66-113.log
   /data/mq/rabbitmq_server-3.6.15/var/log/rabbitmq/rabbit@VM-66-113-sasl.log

Stack trace:
   [{gen,do_for_proc,2,[{file,"gen.erl"},{line,228}]},
    {gen_event,rpc,2,[{file,"gen_event.erl"},{line,239}]},
    {rabbit,ensure_working_log_handlers,0,
            [{file,"src/rabbit.erl"},{line,856}]},
    {rabbit,'-boot/0-fun-0-',0,[{file,"src/rabbit.erl"},{line,288}]},
    {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,424}]},
    {init,start_em,1,[]},
    {init,do_boot,3,[]}]

=INFO REPORT==== 23-Jul-2018::21:45:15.011802 ===
Error description:
   noproc

Log files (may contain more information):
   /data/mq/rabbitmq_server-3.6.15/var/log/rabbitmq/rabbit@VM-66-113.log
   /data/mq/rabbitmq_server-3.6.15/var/log/rabbitmq/rabbit@VM-66-113-sasl.log

Stack trace:
   [{gen,do_for_proc,2,[{file,"gen.erl"},{line,228}]},
    {gen_event,rpc,2,[{file,"gen_event.erl"},{line,239}]},
    {rabbit,ensure_working_log_handlers,0,
            [{file,"src/rabbit.erl"},{line,856}]},
    {rabbit,'-boot/0-fun-0-',0,[{file,"src/rabbit.erl"},{line,288}]},
    {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,424}]},
    {init,start_em,1,[]},
    {init,do_boot,3,[]}]

{"init terminating in do_boot",noproc}
init terminating in do_boot (noproc)

Crash dump is being written to: erl_crash.dump...done

请问下，这是什么原因呢？

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
This plugin has been deprecated [for close to a year](https://github.com/rabbitmq/rabbitmq-clusterer#project-status) and RabbitMQ 3.6.x has reached EOL in May 2018. Sorry but our small team doesn't have the resources to investigate this.
