### ISSUE TITLE
Issue with RabbitMQ 3.7.18

### ISSUE THREAD

**Issue by andevani** [rabbitmq/rabbitmq-clusterer#27]
I am trying to use Rabbitmq-clusterer with RabbitMQ 3.7.18. This plugin was working perfectly with  RabbitMQ 3.6.5 
I am using Rabbitmq-clusterer plugin - 1.0.3

Currently, all nodes are able to create their own cluster. RabbitMQ server is working perfectly on each of node. 

Somehow I am not able to setup cluster. 
while executing rabbitmqctl eval 'rabbit_clusterer:status().' It gives "Clusterer is pre-booting. []
ok"

With rabbitmqctl eval 'rabbit_clusterer:apply_config().' command, it is giving "{cannot_apply_config_currently,preboot}" output.

Please help if I am missing anything. Please let me know for more information.

**Comment by lukebakken** [comment]
Hello and thanks for using RabbitMQ.

If you have questions in the future, please ask them on the mailing list first -

https://groups.google.com/forum/#!forum/rabbitmq-users

Carefully read this project's README file: https://github.com/rabbitmq/rabbitmq-clusterer/blob/master/README.md

You no longer should use this plugin, instead use one of the peer discovery plugins that ship with RabbitMQ - https://www.rabbitmq.com/clustering.html

Please use the latest version of RabbitMQ, which is version 3.8.3 at this time.

**Comment by michaelklishin** [comment]
The problem this plugin originally was set out to solve was addressed in RabbitMQ 3.6.7 around node [restart behavior](https://www.rabbitmq.com/clustering.html#restarting) and then more completely in 3.7.0 with the introduction of [peer discovery](https://www.rabbitmq.com/cluster-formation.html) in the core.

It has been unmaintained for some 5 years and completely irrelevant for 3 years now.

**Comment by michaelklishin** [comment]
Curiously today is the day [RabbitMQ 3.7.x general support ends](https://www.rabbitmq.com/versions.html). Perhaps now would be a good time to [upgrade](https://www.rabbitmq.com/upgrade.html) to `3.8.3`.

**Comment by andevani** [comment]
Thank you for the response @michaelklishin  and @lukebakken Will be going with 3.8.3 version of RabbitMQ with one of the peer discovery plugins
