### ISSUE TITLE
Initial configuration of RabbitMQ nodes

### ISSUE THREAD

**Issue by romanek-adam** [rabbitmq/rabbitmq-clusterer#4]
Hi! I have a question on the initial configuration which should be passed to the clusterer plugin.

Suppose I create a number of RabbitMQ nodes, lets say N, all at the same time. I do not know the node names of individual nodes in advance so I can't populate the config upfront.

What should be the initial config for individual nodes, so that they would wait for the actual config to be provided?

I could experiment to find out about that but I'd like to know what's the official way of doing this.

BTW, thanks for this plug-in. It's certainly something which should become the new official clustering method some time soon. Keep up the good work.

**Comment by michaelklishin** [comment]
Questions belong to rabbitmq-users.

This plugin requires a list of nodes to be provided. Its main value proposition is allowing nodes to leave and join in any order. There's another approach to the same problem: [rabbitmq-autocluster](https://github.com/aweber/rabbitmq-autocluster), with which nodes perform discovery similar to e.g. ElasticSearch. Note that this _does not_ allow nodes to be restarted in arbitrary order.

Some combination of both approaches is the plan for a future cluster formation feature(s).

**Comment by romanek-adam** [comment]
OK, let's continue this discussion in https://groups.google.com/forum/#!topic/rabbitmq-users/OocchRIBJ4A
