### ISSUE TITLE
rabbit_clusterer:status() returns "Clusterer is booting" after a node was restarted due to pause_minority

### ISSUE THREAD

**Issue by kkalin78** [rabbitmq/rabbitmq-clusterer#7]
When a node had been paused due to pause_minority and later restored rabbit_clustere:status reports "Cluster is booting". Although the cluster is alive and all nodes including this one are part of the cluster. rabbitmqctl cluster_status shows correct output. I looked at the plugin code and looks like it gets zero notification in this case. RabbitMQ restart is controlled by rabbit itself. 

How to reproduce:
1) Build a cluster using the plugin and set pause_minority
2) Using iptables drop connectivity of one node to other cluster members and wait until it pauses
3) Remove iptables rules to restore the connectivity
4) Check that rabbitmqctl eval 'rabbit_clusterer:status().' returns incorrect status.

**Comment by michaelklishin** [comment]
rabbitmq-clusterer only covers initial cluster formation, not ongoing cluster operations. After the clusterer started cluster nodes, it has absolutely no effect on or awareness of how clustering works.

**Comment by kkalin78** [comment]
Should I rely on rabbitmqctl cluster_status always even if I use the plugin to assembly the cluster?

**Comment by michaelklishin** [comment]
@kkalin78 HTTP API or rabbitmqctl, just like before.
